export const ApiErrorCode = {
  BAD_REQUEST: "BAD_REQUEST",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",

  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",

  EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",
  INVALID_VERIFICATION_TOKEN: "INVALID_VERIFICATION_TOKEN",
  OFFER_ALREADY_REVIEWED: "OFFER_ALREADY_REVIEWED",
  SELF_REVIEW_NOT_ALLOWED: "SELF_REVIEW_NOT_ALLOWED",
  USER_ALREADY_VERIFIED: "USER_ALREADY_VERIFIED",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
} as const;

export type ApiErrorCode = (typeof ApiErrorCode)[keyof typeof ApiErrorCode];
