import type { Metadata } from "next";
import "@mantine/core/styles.css";
import "../styles/globals.css";
import "@gfazioli/mantine-border-animate/styles.css";

import { mantineHtmlProps } from "@mantine/core";
import { Plus_Jakarta_Sans } from "next/font/google";

import { Providers } from "./providers";

const jakarta = Plus_Jakarta_Sans({
  preload: true,
  variable: "--font-jakarta",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Next Mentoris",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <body className={jakarta.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
