import type { Metadata } from "next";
import "../styles/globals.css";
import "@mantine/core/styles.css";
import { ColorSchemeScript, mantineHtmlProps } from "@mantine/core";
import { Raleway } from "next/font/google";

import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "Next Mentoris",
  description: "Generated by create next app",
};

const ralewayFont = Raleway({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full antialiased" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
      </head>

      <body className={`${ralewayFont.className} min-h-dvh`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
