import type { Metadata } from "next";
import "../styles/globals.css";

import { ColorSchemeScript, mantineHtmlProps } from "@mantine/core";
import { Outfit } from "next/font/google";

import { Providers } from "./providers";

const outfit = Outfit({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Next Mentoris",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
      </head>
      <body className={outfit.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
